# Не читать дефолтный /etc/hosts и системный /etc/resolv.conf
no-hosts
no-resolv
no-poll

# Слушать локально
listen-address=127.0.0.1
bind-interfaces
port=53

# Быстрый upstream DNS (Cloudflare + Google fallback)
server=1.1.1.1
server=1.0.0.1
server=8.8.8.8

# Быстрый размер кэша
cache-size=10000

# Подключение собранных баз
addn-hosts=/etc/dnsmasq.hosts
conf-dir=/etc/dnsmasq.d/,*.conf
