user=root
no-resolv
no-poll
port=53

# Апстримы для интернета
server=1.1.1.1
server=1.0.0.1

cache-size=10000

# Канарейки: принудительно отключаем встроенный DoH-клиент в Chromium/Firefox
address=/use-application-dns.net/
address=/dns.google/
address=/dns.google.com/
address=/chrome.cloudflare-dns.com/
address=/mozilla.cloudflare-dns.com/

conf-dir=/etc/dnsmasq.d/,*.conf
