user=root
no-resolv
no-poll
port=53

# Убраны bind-interfaces и listen-address. Теперь dnsmasq доступен для всех процессов внутри образа.
server=1.1.1.1
server=1.0.0.1
server=8.8.8.8

cache-size=10000

# Отстрел DoH канареек - заставляет Chromium/Firefox fallback'нуться на dnsmasq
address=/use-application-dns.net/
address=/dns.google/
address=/dns.google.com/
address=/chrome.cloudflare-dns.com/
address=/mozilla.cloudflare-dns.com/

conf-dir=/etc/dnsmasq.d/,*.conf


